name: Update Docker Hub Overview with README

on:
  push:
    branches:
      - simple

jobs:
  update-overview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Docker Hub repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: buildwithdan/flask-portfolio